<a href="https://colab.research.google.com/github/Surya-0804/CodingNinjas-Problem/blob/main/pytorchdemo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np


In [ ]:
def defineMatrix(n,m):
    return np.random.rand(n,m)
def matrixMultiplication(A,B):
    n=len(A)
    m=len(A[0])
    o=len(B)
    p=len(B[0])
    if n!=p:
        return false
    c=[ [0 for _ in range(o)] for _ in range(n)]
    for i in range(n):
        for j in range(m):
            c[i][j]=0
            for k in range(o):
                c[i][j]+=A[i][k]*B[k][j]
    print(c)
a=[[1,2],[3,4]]
b=[[2,3],[4,5]]
matrixMultiplication(a,b)

[[10, 13], [22, 29]]


In [ ]:
a=[[1,2],[3,4]]
b=[[2,3],[4,5]]
get_ipython().run_line_magic('time', 'C=matrixMultiplication(a,b)')

[[10, 13], [22, 29]]
CPU times: user 584 µs, sys: 0 ns, total: 584 µs
Wall time: 510 µs


In [ ]:
A=torch.rand(100,100)
B=torch.rand(100,100)
get_ipython().run_line_magic('time', 'C = torch.matmul(A, B)')

CPU times: user 210 µs, sys: 0 ns, total: 210 µs
Wall time: 218 µs


In [ ]:
A=torch.rand(100,100)
B=torch.rand(100,100)
get_ipython().run_line_magic('time', 'C = torch.matmul(A, B)')

CPU times: user 211 µs, sys: 39 µs, total: 250 µs
Wall time: 259 µs


In [ ]:
A=torch.rand(100,100)
B=torch.rand(100,100)
get_ipython().run_line_magic('time', 'C = torch.matmul(A, B)')

CPU times: user 153 µs, sys: 0 ns, total: 153 µs
Wall time: 156 µs


In [ ]:
A=np.random.rand(3,4)
t=torch.tensor(A)
t


tensor([[0.0517, 0.6362, 0.2485, 0.4455],
        [0.3092, 0.9678, 0.7687, 0.7545],
        [0.7439, 0.6929, 0.8119, 0.4928]], dtype=torch.float64)

In [ ]:
torch.randn(2,9)


tensor([[ 0.8179, -1.0079, -0.5173,  0.3620,  0.4031, -0.5202, -1.2752,  0.8388,
          1.7156],
        [ 1.4099, -1.2256, -0.4583,  1.0424,  0.9725, -0.5317,  0.5723, -0.1367,
          0.8760]])

In [ ]:
torch.empty((5,7),dtype=torch.float16)

tensor([[-1.8463e-03,  2.9104e+04,  2.0812e+02,  0.0000e+00,  1.0529e-03,
          2.3904e+04,  2.0812e+02],
        [ 0.0000e+00,  3.3264e-03, -2.5918e+00,         nan,  0.0000e+00,
          5.9605e-08,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  4.7684e-07,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00]], dtype=torch.float16)

In [ ]:
torch.logspace(-1,3,10)

tensor([1.0000e-01, 2.7826e-01, 7.7426e-01, 2.1544e+00, 5.9948e+00, 1.6681e+01,
        4.6416e+01, 1.2915e+02, 3.5938e+02, 1.0000e+03])

In [ ]:
torch.linspace(1,10,8)

tensor([ 1.0000,  2.2857,  3.5714,  4.8571,  6.1429,  7.4286,  8.7143, 10.0000])